<?php
if(!is_file(RootDir.'Install/Install.lock')){
	SysInfo(array(
		"Title"=>"安装锁未放置",
		"Code"=>"40350",
		"Info"=>"程序未安装",
		"Text"=>"您的安装锁未配置正确。<br>为了保证您的网站安全，<br>在没有放置安装锁的情况下，网站会停止运行。<br>正在为您跳转...<script>setTimeout(function(){location.href='/Install'},3000)</script>",
	));
}